id: P006928
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:15.521254
source_metadata:
  id: bdr:W12094
  title: མངོན་པ་མཛོད་གསལ་བྱེད་ལེགས་པར་བཤད་པའི་རྒྱ་མཚོ
  author: ''
  volumes:
    87b414d2ab834deba6b6d6ec43972ce7:
      image_group_id: I2768
      title: ''
      volume_number: 1
      total_pages: 682
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
